<a href="https://colab.research.google.com/github/heunjinkwon/pr/blob/master/homework02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
# 텐서 생성
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [4]:
import tensorflow as tf
c1 = tf.constant([[1, 2], [3, 4]])
c2 = tf.constant([[4, 7], [-1, 0]])
e = tf.constant([[1, 0], [0, 1]]) # 단위 행렬
v1 = tf.Variable([[10, 9], [8, 7]])
v2 = tf.Variable([[3, 6], [5, -1]])

def sRun(input):
  with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    rst = input.eval()
    print(rst)
    return(rst)

sRun(tf.add(c1, c2))
sRun(tf.add_n([c1, c2, c1]))
sRun(tf.add(c1, v1))



[[5 9]
 [2 4]]
[[ 6 11]
 [ 5  8]]
[[11 11]
 [11 11]]


array([[11, 11],
       [11, 11]], dtype=int32)